---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      restartPolicy: Always
      containers:
        - name: gateway-service
          image: adrian2606/gateway-service:v1
          env:
            - name: APP_MODEL
              value: monolith
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: gateway-service-port
  selector:
    app: gateway-service
  type: NodePort
