---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-service
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: microservice-service
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-service
    spec:
      restartPolicy: Always
      containers:
        - name: microservice-service
          image: adrian2606/microservice-service:v3
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: users
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-microservice:3306/users
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  labels:
    app: microservice-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: microservice-service-port
  selector:
    app: microservice-service
  type: NodePort
