apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-microservice
spec:
  selector:
    matchLabels:
      app: mysql-microservice
  template:
    metadata:
      labels:
        app: mysql-microservice
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: users

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-microservice
spec:
  type: ClusterIP
  selector:
    app: mysql-microservice
  ports:
    - port: 3306